- README.md
- setup.py
> docs: add Installation notes to README

- aplt/runner.py
- aplt/tests/__init__.py
> feat: add verification of testplan args, and scenario function arguments

- README.md
- SCENARIOS.md
Closes #4 
@jrconlin, @rpappalax  r?
> docs: add scenario docs and link from readme

- aplt/scenarios.py
> feat: add connect and idle forever scenario for connection load-testing

- .clog.toml
- CHANGELOG.md
> chore: 0.1 release

- .clog.toml
- CHANGELOG.md
> chore: fix clog config and regenerate working links for changelog

- aplt/client.py
- aplt/runner.py
> bug: pass TTL to the send notification call

- aplt/runner.py
> fix: include ttl header for all notifications

- SCENARIOS.md
- aplt/commands.py
> fix: use hyphenated uuid's for latest autopush normalization

- Dockerfile
- README.md
- aplt/runner.py
- setup.py
Peg's autobahn/twisted to newer versions and fixes logging to avoid
displaying DEBUG level autobahn log messages.
Closes #36
Closes #37 
@jrconlin r?
> fix: peg newer library deps and fix logging

- aplt/runner.py
- aplt/tests/__init__.py
> feat: add ability to call class methods

- SCENARIOS.md
- aplt/runner.py
- aplt/scenarios.py
- aplt/tests/__init__.py
- aplt/tests/test_vapid.py
- aplt/vapid.py
- setup.py
Added ability to specify keyword arguments to load plans. Add them as
a dict to the SCENARIO_ARGS list. Multiple dicts will be merged. These
will be stored in scenario._scenario_kw.
Closes #33
@bbangert r?
> feat: Add vapid support

- .gitignore
- README.md
- aplt/client.py
- aplt/scenarios.py
- aplt/tests/__init__.py
- aplt/utils.py
> Add new operational scenarios

- README.md
> docs: add 'supported platforms' notes to README

- aplt/scenarios.py
* _api_test
* _loadtest
also, add additional operational scenario:
* notification_forever_stored
r? @bbangert 
Closes #48
> feat: add wrapper scenarios for api, load testing

- README.md
- aplt/tests/__init__.py
r? @pjenvey 
Closes #57
Closes #60
> docs: update README with notes on installing cryptography and using pypy2-v5.3.1

- .travis.yml
- Dockerfile
> chore: upgrade pypy Docker/travis pypy versions

- aplt/runner.py
- aplt/utils.py
> feat: add support for client ssl certs w/ endpoint connections

- aplt/runner.py
- aplt/utils.py
> feat: allow specifying client certs content via env vars

- aplt/client.py
- aplt/runner.py
- aplt/scenarios.py
so it can pin to a specific partner endpoint
also fix some notification received metrics
closes #79
> feat: add a --endpoint hardcode option

- Dockerfile
- README.md
- requirements.txt
- setup.py
fixing the bad txstatsd dep in setup.py
also update docker's pypy and try out -slim
fixes #94
> fix: migrate reqs to a requirements file

- Dockerfile
useful for ardere's orchestration
fixes #96
> feat: include wget in the docker container

- aplt/scenarios.py
Fixes stored forever to utilize the storage and properly drain it.
Added a new scenario that verifies the servers ability to directly
route a message then save it back to the server when a client drops
without ack'ing it.
> feat: fix the stored forever and add direct storage test

- SCENARIOS.md
- SMOKETEST.md
- aplt/client.py
- aplt/commands.py
- aplt/logobserver.py
- aplt/runner.py
- aplt/scenarios.py
- aplt/tests/__init__.py
- aplt/tests/test_logging.py
- aplt/tests/test_utils.py
- config.ini.sample
- requirements.txt
add json/human logging
add default package
add default websocket
BREAKING: change order of args
Closes #99, mozilla-services/push-okr#40
> feat: molotov smoke test integration

- SMOKETEST.md
- aplt/client.py
- aplt/logobserver.py
- aplt/runner.py
- aplt/scenarios.py
- aplt/tests/__init__.py
- aplt/tests/test_logging.py
- aplt/tests/test_vapid.py
Also simplify how keyword args can be passed
Closes #107
> bug: ensure command line keywork arguments are passed to scenarios

- aplt/logobserver.py
- aplt/scenarios.py
- aplt/tests/__init__.py
- aplt/tests/test_logging.py
- requirements.txt
* Updated dependencies to more modern versions
* labeled parameters for functions to fix potential assignment issues.
* flake8 fix
Closes #116
> bug: remove unused argument, update libraries
